apiVersion: 1

datasources:
  - name: Jaeger
    type: jaeger
    uid: jaeger
    url: http://jaeger:16686
    access: proxy
    isDefault: false
    editable: true
    jsonData:
      tracesToLogsV2:
        datasourceUid: 'loki'
        filterByTraceID: true
        filterBySpanID: false
        tags: ['service.name', 'job']
      tracesToMetrics:
        datasourceUid: 'prometheus'
        tags: [{ key: 'service.name', value: 'service' }]
      nodeGraph:
        enabled: true
      spanBar:
        type: 'None'
