# API Gateway
spring:
  application:
    name: api-gateway
  config:
    import: optional:file:./config/api-gateway.yml
  cloud:
    gateway:
      server:
        webflux:
          routes: [ ]

server:
  port: 8080
